[package]
name = "twox-hash"
version = "1.0.0"
authors = ["Jake Goulding <jake.goulding@gmail.com>"]

description = "A Rust implementation of the XXHash algorithm"
readme = "README.md"
keywords = ["hash"]

homepage = "https://github.com/shepmaster/twox-hash"
repository = "https://github.com/shepmaster/twox-hash"
documentation = "https://docs.rs/twox-hash/"

license = "MIT"

[features]
unstable = []

[dependencies]
rand = "0.3"

[dev-dependencies]
fnv = "1.0"
